config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  get 'pages/vip'

  root 'drivers#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get 'drivers', to: "drivers#index"
  # get 'drivers/new', to: "drivers#new", as: :new_driver
  # get 'drivers/:id', to: "drivers#show", as: :driver
  # post 'drivers', to: "drivers#create"
  # get 'drivers/:id/edit', to: 'drivers#edit', as: :edit_driver
  # patch 'drivers/:id', to: 'drivers#update'
  # delete 'drivers/:id', to: 'drivers#destroy'

  resources :drivers do
    resources :cars
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :driver
end

app/models/driver.rb
class Driver < ApplicationRecord
    has_many :cars, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    before_action :set_driver
  
    def new
      @car = @driver.cars.new
    end
  
    def create
      @driver.cars.create(car_params)
      redirect_to @driver
    end
  
    private
  
    def set_driver
      @driver = Driver.find(params[:driver_id])
    end
  
    def car_params
      params.require(:car).permit(:brand_name, :downforce, :topspeed)
    end
  end
  

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
    before_action :authenticate_user!

    before_action :set_driver, only: [:show, :edit, :update, :destroy]
    
    def index
        @drivers = Driver.all
    end

    def show
        @cars = @driver.cars
    end

    def new
        @driver = Driver.new
    end

    def create
        Driver.create(driver_params)

        redirect_to drivers_path
    end

    def edit
        
    end

    def update
        
         @driver.update(driver_params)

        redirect_to @driver
    end

    def destroy
        driver = Driver.find(params[:id])
      
        driver.destroy

        redirect_to drivers_path
    end

    private

    def set_driver
        @driver = Driver.find(params[:id])
    end

    def driver_params
        params.require(:driver).permit(:first_name, :last_name, :wins)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  
  def home
  end

  def vip
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def render_field(form, attribute, label_text)
        content_tag(:div, class: 'field') do
          form.label attribute, label_text +
            form.text_field(attribute)
        end
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cars/new.html.erb
<h1 class= "signinfo">New car for <%= @driver.first_name %></h1>

<%= form_for [@driver, @car] do |f| %>

 <div class='field'>
 <%= f.label :brand_name, 'Brand name' %>
 <%= f.text_field :brand_name %>
 </div>

 <div class='field'>
 <%= f.label :topspeed, 'Topspeed' %>
 <%= f.text_field :topspeed %>
 </div>

 <div class='field'>
 <%= f.label :downforce, 'Downforce' %>
 <%= f.text_field :downforce %>
 </div>

 <%= f.submit 'Confirm'%>

    <% end %>

app/views/drivers/_form.html.erb
<%= form_for @driver do |f| %>
    <% attribute_fields = {
      first_name: { label: 'Firstname', placeholder: 'Input firstname...' },
      last_name: { label: 'Lastname', placeholder: 'Input lastname...' },
      wins: { label: 'Wins', placeholder: 'Write your wins...' }
    } %>
  
    <% attribute_fields.each do |attribute, options| %>
      <div class="field">
        <%= f.label attribute, options[:label] %>
        <%= f.text_field attribute, placeholder: options[:placeholder] %>
      </div>
    <% end %>
  
    <%= f.submit 'Confirm changes', class: 'button' %>
  <% end %>
  

app/views/drivers/edit.html.erb
<h1>Edit <%= @driver.first_name %></h1>
<%= link_to "Back to homepage", driver_path , class: "back-btn"%>

<%= render 'form' %>

app/views/drivers/index.html.erb
<div class="flex-container">
  <h1>Drivers</h1>

  <%= link_to "Create new driver", new_driver_path, class: "create-btn" %>

  <br>

  <div class="tab">
    <table>
      <tr class="tables">
        <th>Driver</th>
        <th>Lastname</th>
        <th>Wins</th>
        <th>Edit/Delete</th>
      </tr>

      <% @drivers.each do |driver| %>
        <tr>
          <td><%= link_to driver.first_name, driver_path(driver), class: "firstname" %></td>
          <td><%= driver.last_name %></td>
          <td><%= driver.wins %></td>
          <td>
            <%= link_to 'Edit', edit_driver_path(driver), class: "edit-btn" %>
            &nbsp;|&nbsp;
            <%= link_to 'Delete', driver_path(driver), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this driver?' }, class: "delete-btn" %>
          </td>
        </tr>

        <% driver.cars.each do |car| %>
          <tr>
            <td colspan="2">Car Name: <%= car.brand_name %></td>
            <td colspan="2">Downforce/Topspeed: <%= car.downforce %>, <%= car.topspeed %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
</div>

app/views/drivers/new.html.erb
<h1>New Driver</h1>


<%= render 'form' %>

app/views/drivers/show.html.erb
<style>
  h1 {
    text-align: center;
    font-size: 24px;
  }

  .back {
    display: inline-block;
    padding: 8px 16px;
    background-color: #007bff;
    color: #fff;
    text-decoration: none;
    border-radius: 4px;
    margin-bottom: 20px;
  }

  h2 {
    font-size: 18px;
    color: #555;
    margin-bottom: 10px;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
  }

  th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
  }

  .row:nth-child(even) {
    # background-color: #f9f9f9;
  }

  strong {
    font-weight: bold;
  }

  em {
    font-style: italic;
  }
</style>

<h1><%= @driver.first_name %></h1>

<%= link_to "Back", drivers_path, class: "back" %>

<h2>Cars:</h2>

<%= link_to "Make a new car", new_driver_car_path(@driver) %>

<table>
  <tr>
    <th>Car name</th>
    <th>Downforce</th>
    <th>Topspeed</th>
  </tr>

  <% @cars.each do |car| %>
  <tr class="row">
    <td><strong><%= car.brand_name %></strong></td>
    <td><em><%= car.downforce %></em></td>
    <td><em><%= car.topspeed %></em></td>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>



<% if user_signed_in? %>
Signed in as <%= current_user.email %>!
&nbsp;|&nbsp;
<%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
<%= link_to "Login", new_user_session_path %>
<%= link_to "Sign up", new_user_registration_path %>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to the home page</h1>

app/views/pages/vip.html.erb
<h1>Vip page</h1>